version: '3'

services:
    workspace:
        container_name: workspace
        image: convenia/php-full:8.1
        volumes:
            - .:/code
        working_dir: /code
        depends_on:
          - mongodb
          - mysql

    mysql:
        container_name: mysql
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: unittest
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
